version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    container_name: postgres
      
  adminer:
    image: adminer
    ports:
      - 8080:8080
    container_name: adminer

  # api:
  #   image: pab-api
  #   ports:
  #     - 8000:8000
  #   environment:
  #     API_HOST_NAME: "0.0.0.0"
  #     API_PORT: 8000
  #     DB_HOST: "192.168.0.6" # private IP
  #     DB_NAME: db
  #     DB_PASSWORD: password
  #     DB_PORT: 5432
  #     DB_TYPE: postgresql+psycopg2
  #     DB_USER: test
  #     AUTH_SECRET_KEY: b227c4c88cb59cce057eeb97728ce835ddd41e6a86af8a9e1f8a1ebe2a006196
  #     AUTH_ALGORITHM: HS256
  #   container_name: api

  # migrations:
  #   image: pab-migrations
  #   environment:
  #     DB_HOST: "192.168.0.6" # private IP
  #     DB_NAME: db
  #     DB_PASSWORD: password
  #     DB_PORT: 5432
  #     DB_TYPE: postgresql+psycopg2
  #     DB_USER: test
  #   container_name: migrations