apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.appName }}
    version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-container
  template:
    metadata:
      labels:
        app: postgres-container
        tier: backend
    spec:
      containers:
        - name: postgres
          image: "postgres:{{ .Values.postgres.imageTag }}" #10.17
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 512Mi
              cpu: "0.5"
            limits:
              memory: 1Gi
              cpu: 1
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvc