version: "3.8"

services:
  redis:
    image: redis:7.0.10
    ports:
      - "6379:6379"

  postgres:
    image: postgres:10.17
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"

  email-server:
    image: dangawne/points-are-bad/email-server:latest
    environment: 
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_REGION: "us-east-1"
      SENDER_EMAIL: ""
      RABBITMQ_USER: "guest"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_PORT: "5672"
      WEB_HOST_NAME: "http://localhost:3000"
    depends_on:
      - rabbitmq

  api-client:
    image: dangawne/points-are-bad/api-client:latest
    ports: 
      - "8020:8020"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      ACCESS_TOKEN_SECRET_KEY: ""
      API_PORT: 8020
      FRONTEND_DOMAIN: "http://localhost:3000"
      PAB_ENVIRONMENT: "dev"
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
      REFRESH_TOKEN_SECRET_KEY: ""

  openapi:
    image: dangawne/points-are-bad/swagger-ui:latest
    ports:
      - "5000:8080"
