apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.appName }}
    version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.global.appName }}-nginx"
  template:
    metadata:
      labels:
        app: "{{ .Values.global.appName }}-nginx"
    spec:
      containers:
        - image: "nginx:{{ .Values.nginx.imageTag }}"
          name: nginx-container
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: "0.5"
            limits:
              memory: 1Gi
              cpu: 1
          readinessProbe:
            httpGet:
              port: 80
              path: /docs
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              port: 80
              path: /docs
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config