apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: points-are-bad
  labels:
    app: points-are-bad
data:
  default.conf: |
    upstream points_are_bad {
        server api-service:8000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://points_are_bad;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }