apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.appName }}
    version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.backend.api.replicas }}
  selector:
    matchLabels:
      app: api-container
  template:
    metadata:
      labels:
        app: api-container
        tier: backend
    spec:
      initContainers:
        - name: check-db-ready
          image: "postgres:{{ .Values.postgres.imageTag }}"
          command: ['sh', '-c', 
            'until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432; 
            do echo waiting for database; sleep 2; done;']
      containers:
        - name: api
          image: "{{ .Values.backend.imageName }}:{{ .Values.backend.imageTag }}"
          command: ['python', 'main.py']
          envFrom:
            - secretRef:
                name: api-secrets
          ports:
            - containerPort: 8000
              name: fastapi
          resources:
            requests:
              memory: 512Mi
              cpu: "0.5"
            limits:
              memory: 1Gi
              cpu: 1
          readinessProbe:
            httpGet:
              port: 8000
              path: /docs
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              port: 8000
              path: /docs
            initialDelaySeconds: 20
            periodSeconds: 20
      imagePullSecrets:
        - name: regcred

