FROM ubuntu:20.04 AS build-image

RUN apt-get update

ENV NODE_VERSION=14.15.5

# Install NPM
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"

COPY docker/nginx.conf /nginx.conf

WORKDIR /app

COPY ./frontend/ /app/

RUN npm install

RUN npm run build

FROM nginx:1.15 AS run-image

COPY --from=build-image /app/dist/ /usr/share/nginx/html

COPY --from=build-image /nginx.conf /etc/nginx/conf.d/default.conf