apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.appName }}
    version: {{ .Chart.AppVersion }}
data:
  # Data must be encoded in base 64
  POSTGRES_DB: {{ .Values.secrets.dbName }}
  POSTGRES_USER: {{ .Values.secrets.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword }}
  PGDATA: {{ .Values.secrets.pgData }}