apiVersion: batch/v1
kind: Job
metadata:
  name: migrations-job
  namespace: points-are-bad
  labels:
    app: points-are-bad
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          command: ['sh', '-c', 
            'until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432; 
            do echo waiting for database; sleep 2; done;']
      containers:
      - name: migrations-job
        image: dangawne/points-are-bad-api:latest
        command: ["python",  "run_migrations.py"]
        envFrom:
          - secretRef:
              name: migrations-secrets
      restartPolicy: Never
  backoffLimit: 10