apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.appName }}
    version: {{ .Chart.AppVersion }}
spec:
  type: NodePort
  selector:
    app: "{{ .Values.global.appName }}-nginx"
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009