apiVersion: v1
data:
  # Read only access secret
  .dockerconfigjson: {{ .Values.secrets.dockerConfig }}
kind: Secret
metadata:
  labels:
    app: {{ .Values.global.appName }}
    version: {{ .Chart.AppVersion }}
  name: regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson