apiVersion: v1
data:
  # Read only access secret
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJkYW5nYXduZSIsInBhc3N3b3JkIjoiZGNrcl9wYXRfR2RYTUtONUtpWThBZ3hkbUd1YThsNXdRd1ZRIiwiZW1haWwiOiJkYW5nYXduZUBvdXRsb29rLmNvbSIsImF1dGgiOiJaR0Z1WjJGM2JtVTZaR05yY2w5d1lYUmZSMlJZVFV0T05VdHBXVGhCWjNoa2JVZDFZVGhzTlhkUmQxWlIifX19
kind: Secret
metadata:
  labels:
    app: points-are-bad
    version: {{ .Chart.AppVersion }}
  name: regcred
  namespace: {{ .Release.Namespace }}
  resourceVersion: "50661"
  uid: 62555734-8f7a-4c50-b908-758dc96af452
type: kubernetes.io/dockerconfigjson