apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: points-are-bad
  labels:
    app: points-are-bad
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: api-container