"""empty message

Revision ID: 5c71dbd39513
Revises: 4936ecc4425f
Create Date: 2022-12-17 10:29:06.630755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c71dbd39513'
down_revision = '4936ecc4425f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
