apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.appName }}
    version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-container
  template:
    metadata:
      labels:
        app: redis-container
        tier: backend
    spec:
      containers:
        - image: "redis:{{ .Values.redis.imageTag }}" 
          envFrom:
            - secretRef:
                name: redis-secrets