apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.appName }}
    version: {{ .Chart.AppVersion }}
data:
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword }}
  REDIS_REQUIREPASS: {{ .Values.secrets.redisPassword }}