apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.appName }}
    version: {{ .Chart.AppVersion }}
data:
  AUTH_SECRET_KEY: {{ .Values.secrets.authSecretKey }}
  DB_NAME: {{ .Values.secrets.dbName }}
  DB_USER: {{ .Values.secrets.dbUser }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  DB_TYPE: {{ .Values.secrets.dbType }}
  DB_HOST: {{ .Values.secrets.dbHost }}