apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.appName }}
    version: {{ .Chart.AppVersion }}
data:
  REDIS_HOST: {{ .Values.secrets.redisHost }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword }}
  DB_NAME: {{ .Values.secrets.dbName }}
  DB_USER: {{ .Values.secrets.dbUser }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  DB_TYPE: {{ .Values.secrets.dbType }}
  DB_HOST: {{ .Values.secrets.dbHost }}
  ACCESS_TOKEN_SECRET: {{ .Values.secrets.accessTokenSecret }}
  REFRESH_TOKEN_SECRET: {{ .Values.secrets.refreshTokenSecret }}
  CSRF_TOKEN_SECRET: {{ .Values.secrets.csrfTokenSecret }}