apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: points-are-bad
  labels:
    app: points-are-bad
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /run/desktop/mnt/host/c/postgres
  storageClassName: local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop # name of the node
