apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: points-are-bad
  labels:
    app: points-are-bad
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-container